[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-site-checker"
version = "0.2"
requires-python = ">=3.6"
dependencies = []

[project.scripts]
ssc = "ssc.cli:main"